# spring configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/halmisae?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul  # local DB connection
#    url: jdbc:mysql://localhost:3307/halmisae?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul  # SSH RDS connection
#    url: jdbc:mysql://mydb2.cz882eka271p.ap-northeast-2.rds.amazonaws.com:3306/halmisae?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul # HTTP RDS connection
    username: root
    password: 1111  # local DB password
#    password: kosta6006!  # RDS password
  messages:
    basename: custom-error-messages
  application:
    name: halmisae
  # JPA Hibernate configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        id:
          new_generator_mappings: true
        jdbc:
          batch_size: 30
# default error message
server:
  error:
    whitelabel:
      enabled: true

# s3 setting
cloud:
  aws:
    credentials:
      access-key: AKIA2UC3CMQGZLFAI3FX
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: halmisae-final
    stack:
      auto: false


## JWT TokenProvider
#jwt:
#  issuer: tmddn1679@naver.com
#  secret_key: halmisae