# spring configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/halmisae?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul  # 로컬 DB 접속
#    url: jdbc:mysql://localhost:3307/halmisae?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul  # SSH 접속
#    url: jdbc:mysql://mydb2.cz882eka271p.ap-northeast-2.rds.amazonaws.com:3306/halmisae?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul # HTTP 접속
    username: root
    password: kosta6006!
  messages:
    basename: custom-error-messages
  application:
    name: halmisae
  # JPA Hibernate configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        id:
          new_generator_mappings: true
        jdbc:
          batch_size: 30
# default error message
server:
  error:
    whitelabel:
      enabled: true

## JWT TokenProvider
#jwt:
#  issuer: tmddn1679@naver.com
#  secret_key: halmisae